version: "3"

services:
  db:
    build:
      context: ./docker/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_API_USER=api
      - POSTGRES_API_USER_PASSWORD=test
      - POSTGRES_READONLY_USER_NAME=readonly
      - POSTGRES_READONLY_USER_PASSWORD=readonlyPassword
    ports:
      - "5434:5432"
    volumes:
      - hnk-pgdata:/var/lib/postgresql/data

  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-beta.3
    ports:
      - 8080:8080
    depends_on:
      - db
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:test@db:5432/hnk_dev
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: $HASURA_SECRET
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS256","jwk_url": "$DOCKER_HOST_URL:$API_PORT/jwk"}'

volumes:
  hnk-pgdata:
